/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Arayuz;

import javax.swing.JOptionPane;

/**
 *
 * @author Aldemir
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_KullanıcıAdı = new javax.swing.JLabel();
        txt_KullaniciAdi = new javax.swing.JTextField();
        lbl_sifre = new javax.swing.JLabel();
        txt_sifre = new javax.swing.JTextField();
        btn_Giris = new javax.swing.JButton();
        btn_geri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_KullanıcıAdı.setText("Kullanıcı Adı:");

        txt_KullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_KullaniciAdiActionPerformed(evt);
            }
        });

        lbl_sifre.setText("Şifre: ");

        txt_sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sifreActionPerformed(evt);
            }
        });

        btn_Giris.setText("Giris");
        btn_Giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GirisActionPerformed(evt);
            }
        });

        btn_geri.setText("Geri");
        btn_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_KullanıcıAdı)
                                .addGap(18, 18, 18)
                                .addComponent(txt_KullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btn_Giris))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_geri)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_geri)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_KullanıcıAdı)
                    .addComponent(txt_KullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sifre)
                    .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btn_Giris)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sifreActionPerformed

    private void btn_GirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GirisActionPerformed
        // TODO add your handling code here:
       /* String kullanıcıAdı = "a";
        String şifre = "a";
        while (true) {
            if (!(txt_KullaniciAdi.getText().equals(kullanıcıAdı) && txt_sifre.getText().equals(şifre))) {
                JOptionPane.showMessageDialog(null, "Tekrar Deneyiniz");
                break;
            }
            if (txt_KullaniciAdi.getText().equals(kullanıcıAdı) && txt_sifre.getText().equals(şifre)) {
                insideAdmin Frame = new insideAdmin();
                Frame.setVisible(true);
                this.dispose();
                break;
       
       
            }
        
        */
       Admin A = new Admin(txt_KullaniciAdi.getText(),txt_sifre.getText());
       
       while (true){
       /*if(A.getkad().equals("a") && A.getsifre().equals("a"))
       {
             insideAdmin Frame = new insideAdmin();
                Frame.setVisible(true);
                this.dispose();
                break;
       }
      else   {
                JOptionPane.showMessageDialog(null, "Tekrar Deneyiniz");
                break;
            }*/
            if(A.login(txt_KullaniciAdi.getText(),txt_sifre.getText())){
                insideAdmin Frame = new insideAdmin();
                Frame.setVisible(true);
                this.dispose();
                break;
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Tekrar Deneyiniz");
                break;
            }
       }
       
       
       
    }//GEN-LAST:event_btn_GirisActionPerformed

    private void btn_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriActionPerformed
        Ev geri = new Ev();
        geri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_geriActionPerformed

    private void txt_KullaniciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_KullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_KullaniciAdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Giris;
    private javax.swing.JButton btn_geri;
    private javax.swing.JLabel lbl_KullanıcıAdı;
    private javax.swing.JLabel lbl_sifre;
    private javax.swing.JTextField txt_KullaniciAdi;
    private javax.swing.JTextField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
